# Generated by Django 4.2.1 on 2023-05-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0002_rename_content_code_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='snippet',
            field=models.TextField(default=None, null=True),
        ),
    ]
