# Generated by Django 4.2.1 on 2023-05-28 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0003_alter_code_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='code_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='codeapp.code'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
